# Generated by Django 4.0.4 on 2022-06-14 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risersizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='Riser Sizing', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.CharField(blank=True, max_length=200)),
                ('pipe_category', models.CharField(choices=[('', 'Choose...'), ('DOI', 'DOI oil or gas pipeline'), ('DOT_liquid', 'DOT liquid pipeline'), ('DOT_gas', 'DOT gas pipeline')], max_length=200)),
                ('pipe_OD', models.FloatField(verbose_name='riser outer diameter (in)')),
                ('pipe_WT_corr', models.FloatField(verbose_name='riser wall thickness corrosion allowance (in)')),
                ('pipe_base_WD', models.FloatField(verbose_name='riser base water dpeth (ft)')),
                ('fluid_density', models.FloatField(verbose_name='riser content fluid density during operation (lb/ft3)')),
                ('hydro_density', models.FloatField(default=64.0, verbose_name='riser hydrotest fluid density, usually seawater (lb/ft3)')),
                ('outer_density', models.FloatField(default=64.0, verbose_name='riser surrounding fluid density, usually seawater (lb/ft3)')),
                ('pressure_refer', models.FloatField(default=0.0, help_text='This is the reference pressure used to calculate pressures at other locations.        The reference pressure can be shut-in tubing pressure at subsea well,        or the pressure at BSDV at the surface. If a value of 0.0 is left in this box,        the pressure at the surface and at the riser base should be provided.', verbose_name='pressure at the reference location (psi)')),
                ('WD_refer', models.FloatField(default=0.0, verbose_name='water depth at the reference location (ft)')),
                ('pressure_surf', models.FloatField(default=0.0, help_text='If a value of 0.0 is left in this box, the pressure will be repalced        by a calculated pressure based on the reference pressure.        User can also input a value to overide the calculation value.', verbose_name='riser design pressure at the surface (psi)')),
                ('pressure_base', models.FloatField(default=0.0, help_text='If a value of 0.0 is left in this box, the pressure will be repalced        by a calculated pressure based on the reference pressure.        User can also input a value to overide the calculation value.', verbose_name='riser internal design pressure at the riser base (psi)')),
                ('hydro_factor', models.FloatField(verbose_name='hydrotest factor or the ratio of hydrotest pressure to design pressure')),
                ('SMYS', models.FloatField(verbose_name='riser specified minimum yield strength (SMYS, psi)')),
                ('SMUTS', models.FloatField(verbose_name='riser specified minimum ultimate tensile strength (SMUTS, psi)')),
                ('F_E', models.FloatField(default=1.0, verbose_name='longitudinal/seam joint factor')),
                ('F_hoop', models.FloatField(default=0.6, help_text='Applicable to code 30 CFR 250, API 1111, 49 CFR 195, ASME B31.4.         do not change the default value unless project requried.', verbose_name='design factor for hoop stress')),
                ('F_hoop_gas', models.FloatField(default=0.5, verbose_name='design factor for hoop stress (49CFR192, B31.8)')),
                ('F_hydro', models.FloatField(default=0.75, verbose_name='design factor for hydrotest presssure (API 1111)')),
                ('k_burst', models.FloatField(default=0.45, help_text='Can be inreased to 0.5 for improved mechanical properties and        dimenisons control per API RP 1111 Annex B.', verbose_name='a parameter to account for mechinical properties')),
                ('Tp', models.FloatField(verbose_name='riser content temperature, deg F')),
                ('E_YM', models.FloatField(verbose_name="riser pipe Young's Modulus (psi)")),
                ('PR', models.FloatField(default=0.3, verbose_name="Poisson's ratio (0.3 for steel)")),
                ('F_c', models.FloatField(default=0.7, verbose_name='collapse factor')),
                ('designPressure_base', models.FloatField(default=0.0)),
                ('designHydroPre_surf', models.FloatField(default=0.0)),
                ('designHydroPre_base', models.FloatField(default=0.0)),
                ('F_T', models.FloatField(default=1.0)),
                ('WT_30cfr250_1', models.FloatField(default=0.0)),
                ('WT_30cfr250_2', models.FloatField(default=0.0)),
                ('WT_30cfr250', models.FloatField(default=0.0)),
                ('WT_api1111_design_1', models.FloatField(default=0.0)),
                ('WT_api1111_design_2', models.FloatField(default=0.0)),
                ('WT_api1111_design', models.FloatField(default=0.0)),
                ('WT_api1111_hydro_1', models.FloatField(default=0.0)),
                ('WT_api1111_hydro_2', models.FloatField(default=0.0)),
                ('WT_api1111_hydro', models.FloatField(default=0.0)),
                ('WT_api1111', models.FloatField(default=0.0)),
                ('WT_49cfr195_1', models.FloatField(default=0.0)),
                ('WT_49cfr195_2', models.FloatField(default=0.0)),
                ('WT_49cfr195', models.FloatField(default=0.0)),
                ('WT_b31p4_1', models.FloatField(default=0.0)),
                ('WT_b31p4_2', models.FloatField(default=0.0)),
                ('WT_b31p4', models.FloatField(default=0.0)),
                ('WT_49cfr192_1', models.FloatField(default=0.0)),
                ('WT_49cfr192_2', models.FloatField(default=0.0)),
                ('WT_49cfr192', models.FloatField(default=0.0)),
                ('WT_b31p8_1', models.FloatField(default=0.0)),
                ('WT_b31p8_2', models.FloatField(default=0.0)),
                ('WT_b31p8', models.FloatField(default=0.0)),
                ('WT_collapse_1', models.FloatField(default=0.0)),
                ('WT_collapse_2', models.FloatField(default=0.0)),
                ('WT_collapse', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risersizings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'permissions': [('Risersizing_permit', 'user can access Risersizing')],
            },
        ),
    ]
